### ISSUE TITLE
GStreamer error: gst-stream-error-quark: This appears to be a text file

### ISSUE THREAD

**Issue by timdp** [nilicule/mopidy-audioaddict#8]
I installed this on Mopidy 2.0.0 (with MusicBox WebClient) on Raspbian. When I tried to play a few di.fm streams, nothing happened. The log said:

```
2016-05-23 13:46:18,123 INFO [19339:AudioAddictBackend-3] mopidy_audioaddict.client: AudioAddict: loading 91 channels on Digitally Imported
2016-05-23 13:46:45,098 ERROR [19339:MainThread] mopidy.audio.gst: GStreamer error: gst-stream-error-quark: This appears to be a text file (5)
2016-05-23 13:47:12,010 ERROR [19339:MainThread] mopidy.audio.gst: GStreamer error: gst-stream-error-quark: This appears to be a text file (5)
2016-05-23 13:47:16,833 ERROR [19339:MainThread] mopidy.audio.gst: GStreamer error: gst-stream-error-quark: This appears to be a text file (5)
```

I mostly use Spotify, but occasionally streams too, and those work. Perhaps something changed in Mopidy 2?

**Comment by v-tron** [comment]
I have the exact same problem. Installing every possible gstreamer package (0.10/1.0) didn't fix it either. Anyone have a fix for this?

<code> WARNING  2016-07-11 12:55:50,662 [3030:Core-13] mopidy.core.tracklist
  Track is not playable: audioaddict:channel:124

DEBUG    2016-07-11 12:55:50,711 [3030:Audio-2] mopidy.audio.gst
  Changing state to GST_STATE_READY: result=GST_STATE_CHANGE_SUCCESS

INFO     2016-07-11 12:55:50,718 [3030:AudioAddictBackend-3] mopidy_audioaddict.actor
  Stream URL: http://listen.di.fm/premium_high/oldschoolhouse.pls?###

DEBUG    2016-07-11 12:55:50,725 [3030:AudioAddictBackend-3] mopidy_audioaddict.actor
  Unwrapping stream from URI: http://listen.di.fm/premium_high/oldschoolhouse.pls?###

DEBUG    2016-07-11 12:55:50,974 [3030:AudioAddictBackend-3] mopidy_audioaddict.actor
  GStreamer failed scanning URI (http://listen.di.fm/premium_high/oldschoolhouse.pls?###): gst-stream-error-quark: This appears to be a text file (5)

DEBUG    2016-07-11 12:55:51,104 [3030:AudioAddictBackend-3] urllib3.connectionpool
  "GET /premium_high/oldschoolhouse.pls?### HTTP/1.1" 200 416

DEBUG    2016-07-11 12:55:51,127 [3030:AudioAddictBackend-3] mopidy_audioaddict.actor
  Parsed playlist (http://listen.di.fm/premium_high/oldschoolhouse.pls?###) and found new URI: http://prem2.di.fm:80/oldschoolhouse_hi?###

DEBUG    2016-07-11 12:55:51,130 [3030:AudioAddictBackend-3] mopidy_audioaddict.actor
  Unwrapping stream from URI: http://prem2.di.fm:80/oldschoolhouse_hi?###

DEBUG    2016-07-11 12:55:51,604 [3030:AudioAddictBackend-3] pykka
  Exception returned from AudioAddictBackend (urn:uuid:###) to caller:

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)

  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(_message['args'], *_message['kwargs'])

  File "/usr/lib/python2.7/dist-packages/mopidy/backend.py", line 245, in change_track
    uri = self.translate_uri(track.uri)

  File "/usr/local/lib/python2.7/dist-packages/Mopidy_AudioAddict-0.3.1-py2.7.egg/mopidy_audioaddict/actor.py", line 123, in translate_uri
    return _unwrap_stream(channel['streamurl'], timeout=self._config['stream']['timeout'], scanner=self._scanner, requests_session=self._session)

  File "/usr/local/lib/python2.7/dist-packages/Mopidy_AudioAddict-0.3.1-py2.7.egg/mopidy_audioaddict/actor.py", line 161, in _unwrap_stream
    scan_result.mime.startswith('text/') or

AttributeError: 'NoneType' object has no attribute 'startswith'</code>

**Comment by axelsimon** [comment]
Any solutions to this? I just ran into the same issue and in all likelihood, this is due to the fact DI.fm and friends changed they're websites something like 6 months ago, but the code for mopidy-audioaddict looks like it hasn't been updated in much longer…

**Comment by ViperEclipse** [comment]
same issue here :( any solution?

**Comment by acromiongames** [comment]
Seems to be caused by the merged pull-request that unwraps the playlists. Either AudioAddict doesn't do that with their playlists anymore, or GStreamer can handle it itself when it does. But it's not needed anymore.

**Comment by kdjordjev** [comment]
hello I have the issue as well.
It seems no progress here.. any idea how to fix it?

**Comment by axelsimon** [comment]
Maybe looking at the code used in recent versions of Clementine or the [Kodi Audioaddict plugin](https://github.com/ssapalski/plugin.audio.addict) could help.
